# --- !Ups

INSERT INTO territories VALUES (1, 'W',  'World', 7243000000, NULL, false, false);
INSERT INTO territories VALUES (2, 'PL', 'Poland', 38483957, 1, true);
INSERT INTO territories VALUES (3, 'GB', 'United Kingdom', 63181775, 1, true);
INSERT INTO territories VALUES (4, 'LT', 'Lithuania', 2921920, 1, true);
INSERT INTO territories VALUES (5, 'NO', 'Norway', 5136700, 1, true);
INSERT INTO territories VALUES (6, 'IS', 'Iceland', 325671, 1, true);
INSERT INTO territories VALUES (7, 'SE', 'Sweden', 9716962, 1, true);
INSERT INTO territories VALUES (8, 'FI', 'Finland', 5474094, 1, true);
INSERT INTO territories VALUES (9, 'EE', 'Estonia', 1315819, 1, true);
INSERT INTO territories VALUES (10, 'LV', 'Latvia', 1990300, 1, true);
INSERT INTO territories VALUES (11, 'DK', 'Denmark', 5655750, 1, true);
INSERT INTO territories VALUES (12, 'DE', 'Germany', 80716000, 1, true);
INSERT INTO territories VALUES (13, 'IE', 'Ireland', 6378000, 1, true);
INSERT INTO territories VALUES (14, 'NL', 'Netherlands', 16856620, 1, true);
INSERT INTO territories VALUES (15, 'BE', 'Belgium', 11198638, 1, true);
INSERT INTO territories VALUES (16, 'LU', 'Luxembourg', 549680, 1, true);
INSERT INTO territories VALUES (17, 'FR', 'France', 66616416, 1, true);
INSERT INTO territories VALUES (18, 'RU', 'Russia', 143900000, 1, true);
INSERT INTO territories VALUES (19, 'BY', 'Belarus', 9475100, 1, true);
INSERT INTO territories VALUES (20, 'UA', 'Ukraine', 44291413, 1, true);
INSERT INTO territories VALUES (21, 'SK', 'Slovakia', 5415949, 1, true);
INSERT INTO territories VALUES (22, 'CZ', 'Czech Republic', 10513209, 1, true);
INSERT INTO territories VALUES (23, 'ES', 'Spain', 46704314, 1, true);
INSERT INTO territories VALUES (24, 'PT', 'Portugal', 10427301, 1, true);
INSERT INTO territories VALUES (25, 'IT', 'Italy', 60782668, 1, true);
INSERT INTO territories VALUES (26, 'CH', 'Switzerland', 8183800, 1, true);
INSERT INTO territories VALUES (27, 'AT', 'Austria', 8572895, 1, true);
INSERT INTO territories VALUES (28, 'HU', 'Hungary', 9877365, 1, true);
INSERT INTO territories VALUES (29, 'RO', 'Romania', 19942642, 1, true);
INSERT INTO territories VALUES (30, 'MD', 'Moldova', 2913281, 1, true);
INSERT INTO territories VALUES (31, 'BG', 'Bulgaria', 7364570, 1, true);
INSERT INTO territories VALUES (32, 'RS', 'Republic of Serbia', 7209764, 1, true);
INSERT INTO territories VALUES (33, 'ME', 'Montenegro', 703208, 1, true);
INSERT INTO territories VALUES (34, 'MK', 'Macedonia', 2058539, 1, true);
INSERT INTO territories VALUES (35, 'GR', 'Greece', 10816286, 1, true);
INSERT INTO territories VALUES (36, 'AL', 'Albania', 3020209, 1, true);
INSERT INTO territories VALUES (37, 'BA', 'Bosnia and Herzegovina', 3871643, 1, true);
INSERT INTO territories VALUES (38, 'HR', 'Croatia', 4284889, 1, true);
INSERT INTO territories VALUES (39, 'SI', 'Slovenia', 2061085, 1, true);
INSERT INTO territories VALUES (40, 'CY', 'Cyprus', 1117000, 1, true);

INSERT INTO territories VALUES (41, 'PLPK', 'Podkarpackie', 2101732, 2, false);
INSERT INTO territories VALUES (42, 'PLMZ', 'Mazowieckie', 5164612, 2, false);
INSERT INTO territories VALUES (43, 'PLLU', 'Lubelskie', 2175251, 2, false);
INSERT INTO territories VALUES (45, 'PLPD', 'Podlaskie', 1197610, 2, false);
INSERT INTO territories VALUES (46, 'PLSW', 'Świętokrzyskie', 1281796, 2, false);

INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rzeszów', 182028, 41, 50.33, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Przemyśl', 64276, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Stalowa Wola', 64189, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mielec', 61238, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tarnobrzeg', 48558, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Krosno', 47307, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Dębica', 47180, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jarosław', 39426, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sanok', 39375, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jasło', 36641, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łańcut', 18143, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Przeworsk', 15915, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ropczyce', 15655, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nisko', 15479, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Leżajsk', 14448, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lubaczów', 12552, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nowa Dęba', 11507, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ustrzyki Dolne', 9521, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kolbuszowa', 9341, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Strzyżów', 8930, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Brzozów', 7631, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sędziszów Małopolski', 7481, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rudnik nad Sanem', 6883, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nowa Sarzyna', 6287, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Dynów', 6195, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Głogów Małopolski', 6014, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Boguchwała', 5796, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jedlicze', 5782, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lesko', 5674, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Radymno', 5528, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zagórz', 5100, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pilzno', 4762, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sokołów Małopolski', 4028, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rymanów', 3753, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pruchnik', 3716, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tyczyn', 3602, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kańczuga', 3242, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Oleszyce', 3108, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Radomyśl Wielki', 3079, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Brzostek', 2697, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sieniawa', 2198, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Dukla', 2194, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Błażowa', 2182, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Narol', 2100, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Cieszanów', 1962, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Iwonicz-Zdrój', 1904, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Przecław', 1682, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Baranów Sandomierski', 1508, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ulanów', 1482, 41, 52.02, 22);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kołaczyce', 1447, 41, 52.02, 22);

INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lublin', 343598, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Chełm', 65481, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zamość', 65255, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Biała Podlaska', 57658, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Puławy', 49100, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Świdnik', 40225, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kraśnik', 35788, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łuków', 30757, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Biłgoraj', 27169, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lubartów', 22543, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łęczna', 19926, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tomaszów Lubelski', 19983, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Krasnystaw', 19539, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Hrubieszów', 18585, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Dęblin', 17057, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Międzyrzec Podlaski', 17117, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Radzyń Podlaski', 16188, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Włodawa', 13643, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Janów Lubelski', 12092, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Parczew', 10953, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ryki', 9955, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Poniatowa', 9646, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Opole Lubelskie', 8860, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Bełżyce', 6765, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Terespol', 5815, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Bychawa', 5178, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Szczebrzeszyn', 5245, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rejowiec Fabryczny', 4515, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nałęczów', 4033, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tarnogród', 3464, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kock', 3412, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zwierzyniec', 3347, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Krasnobród', 3117, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Stoczek Łukowski', 2700, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Piaski', 2672, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kazimierz Dolny', 2607, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Annopol', 2664, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Józefów', 2520, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tyszowce', 2171, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łaszczów', 2187, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ostrów Lubelski', 2207, 43, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Frampol', 1482, 43, 0, 0);

INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Vilnius', 529022, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kaunas', 304012, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Klaipėda', 157305, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Šiauliai', 105610, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Panevėžys', 96328, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Alytus', 56357, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Marijampolė', 38846, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mažeikiai', 35997, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jonava', 29353, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Utena', 27484, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kėdainiai', 25654, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Telšiai', 24295, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tauragė', 23516, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ukmergė', 22510, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Visaginas', 20532, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Plungė', 19153, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kretinga', 18816, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Šilutė', 17002, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Radviliškis', 16527, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Palanga', 15358, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Gargždai', 14937, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Druskininkai', 13762, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rokiškis', 13637, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Biržai', 11666, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Elektrėnai', 11592, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kuršėnai', 11409, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Vilkaviškis', 11038, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Raseiniai', 10890, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jurbarkas', 10878, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Garliava', 10671, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lentvaris', 10610, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Grigiškės', 10394, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Anykščiai', 9968, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Prienai', 9394, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Joniškis', 9309, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Varėna', 8974, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kelmė', 8828, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Naujoji Akmenė', 8532, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kaišiadorys', 8243, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pasvalys', 7138, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kupiškis', 6931, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zarasai', 6779, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Šalčininkai', 6573, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kazlų Rūda', 6342, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Molėtai', 6204, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Širvintos', 6075, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Skuodas', 6032, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Šakiai', 5773, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pabradė', 5723, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ignalina', 5702, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Šilalė', 5454, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Švenčionėliai', 5328, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kybartai', 5223, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nemenčinė', 4933, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pakruojis', 4919, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Švenčionys', 4845, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Trakai', 4837, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Vievis', 4662, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lazdijai', 4357, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kalvarija', 4349, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rietavas', 3574, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Žiežmariai', 3453, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Eišiškės', 3276, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ariogala', 2939, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Neringa', 2752, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Šeduva', 2662, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Akmenė', 2504, 4, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Birštonas', 2475, 4, 0, 0);

INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Białystok', 295282, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Suwałki', 69317, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łomża', 62711, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Augustów', 30610, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Bielsk Podlaski', 26336, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zambrów', 22451, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Grajewo', 22246, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Hajnówka', 21559, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sokółka', 18765, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łapy', 16005, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Siemiatycze', 14766, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kolno', 10579, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Wasilków', 10511, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mońki', 10352, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Czarna Białostocka', 9671, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Wysokie Mazowieckie', 9503, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Dąbrowa Białostocka', 5874, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Choroszcz', 5782, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sejny', 5650, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ciechanowiec', 4840, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Supraśl', 4679, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Brańsk', 3867, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Szczuczyn', 3489, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Michałowo', 3177, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Knyszyn', 2850, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Czyżew', 2636, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Krynki', 2511, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zabłudów', 2495, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lipsk', 2443, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Stawiski', 2379, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Szepietowo', 2282, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Suchowola', 2274, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nowogród', 2197, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Drohiczyn', 2125, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tykocin', 2014, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Goniądz', 1900, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jedwabne', 1717, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Rajgród', 1626, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kleszczele', 1345, 45, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Suraż', 1008 , 45, 0, 0);

INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kielce', 199870, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ostrowiec Świętokrzyski', 72277, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Starachowice', 51158, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Skarżysko-Kamienna', 47538, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sandomierz', 24552, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Końskie', 20281, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Busko-Zdrój', 16694, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Jędrzejów', 15851, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Staszów', 15384, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pińczów', 11306, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Włoszczowa', 10545, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Suchedniów', 8714, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Połaniec', 8347, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Opatów', 6767, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sędziszów', 6707, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Stąporków', 5996, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kazimierza Wielka', 5748, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ożarów', 4730, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Chęciny', 4438, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Małogoszcz', 3929, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Chmielnik', 3921, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ćmielów', 3157, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kunów', 3098, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Daleszyce', 2911, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Wąchock', 2865, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Koprzywnica', 2575, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Bodzentyn', 2274, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Osiek', 2004, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zawichost', 1861, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Skalbmierz', 1315, 46, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Działoszyce', 981 , 46, 0, 0);

INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Warszawa', 1724404, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Radom', 218466, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Płock', 122815, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Siedlce', 76347, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pruszków', 59570, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Legionowo', 54231, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ostrołęka', 52917, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Otwock', 45044, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Piaseczno', 44869, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ciechanów', 44797, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Żyrardów', 41096, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mińsk Mazowiecki', 39880, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Wołomin', 37505, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sochaczew', 37480, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ząbki', 31884, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mława', 30880, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Grodzisk Mazowiecki', 29907, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Marki', 29032, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nowy Dwór Mazowiecki', 28287, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Wyszków', 27222, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Piastów', 22826, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ostrów Mazowiecka', 22796, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Płońsk', 22494, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kobyłka', 20855, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Józefów', 19914, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pionki', 19382, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sulejówek', 19311, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pułtusk', 19228, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Gostynin', 19092, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sokołów Podlaski', 18720, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Sierpc', 18491, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kozienice', 18277, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zielonka', 17398, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Konstancin-Jeziorna', 17391, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Przasnysz', 17326, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Garwolin', 17146, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łomianki', 16639, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Grójec', 16453, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Milanówek', 16410, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Brwinów', 13090, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Węgrów', 12796, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Błonie', 12570, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Szydłowiec', 12064, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Warka', 11727, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Góra Kalwaria', 11685, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Radzymin', 11378, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Ożarów Mazowiecki', 10561, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Karczew', 10160, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Maków Mazowiecki', 10118, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Żuromin', 9022, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zwoleń', 8112, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tłuszcz', 7989, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nasielsk', 7650, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Białobrzegi', 7132, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łosice', 7099, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łochów', 6786, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mszczonów', 6460, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Przysucha', 6146, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Lipsko', 5816, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Iłża', 5054, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Łaskarzew', 4914, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Raciąż', 4662, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Pilawa', 4438, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Skaryszew', 4308, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Gąbin', 4142, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Serock', 4130, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Tarczyn', 4127, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Żelechów', 4081, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Nowe Miasto nad Pilicą', 3920, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Podkowa Leśna', 3869, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Halinów', 3654, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Zakroczym', 3241, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Myszyniec', 3170, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Glinojeck', 3150, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Drobin', 2992, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Chorzele', 2939, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kałuszyn', 2934, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Różan', 2730, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Wyszogród', 2709, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mogielnica', 2386, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Kosów Lacki', 2187, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Brok', 1977, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Bieżuń', 1911, 42, 0, 0);
INSERT INTO cities(name, population, container, latitude, longitude) VALUES ('Mordy', 1819, 42, 0, 0);

# --- !Downs
TRUNCATE TABLE cities CASCADE;
TRUNCATE TABLE territories CASCADE;